/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.util.*;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Viraj Madhushan on 09th June 2020
 */
public class cafe2 extends javax.swing.JFrame {

double [] drink = new double[12];
double [] cake = new double[6];
String [] cost = new String[3];
double [] i = new double [18];
double [] ncost = new double [3];


//=====Price List (Rs.)===============
double iBlackCoffee = 20.0;
double iExpresso = 30; 
double iAmericano = 35;
double iLatte = 35.0;
double iCappuccino = 40.0;
double iMocha = 45.0;
double iBlackTea = 15.0;
double iGreenTea = 20.0;
double iMintTea = 25.0;
double iChocoletTea = 35.0;
double iIceTea = 15.0;
double iHotChocolet = 30.0;

double iCupcake = 20.0;
double iCheesecake = 50.0;
double iTartlet = 55.0;
double iCrossaint = 15.0;
double iRaspberry = 45.0;
double iMuffin = 35.0;
//====================================
/**
     * Creates new form cafe2
     */
    public cafe2() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // this is code for full screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_coffee = new javax.swing.JPanel();
        jCheckBox_blackCoff = new javax.swing.JCheckBox();
        jCheckBox_expresso = new javax.swing.JCheckBox();
        jCheckBox_americano = new javax.swing.JCheckBox();
        jCheckBox_latte = new javax.swing.JCheckBox();
        jCheckBox_cappuccino = new javax.swing.JCheckBox();
        jCheckBox_mocha = new javax.swing.JCheckBox();
        jTextField_expresso = new javax.swing.JTextField();
        jTextField_americno = new javax.swing.JTextField();
        jTextField_latte = new javax.swing.JTextField();
        jTextField_cappucino = new javax.swing.JTextField();
        jTextField_mocha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_blackCoff = new javax.swing.JTextField();
        jPanel_cakes = new javax.swing.JPanel();
        jCheckBox_cupCake = new javax.swing.JCheckBox();
        jCheckBox_cheeseCake = new javax.swing.JCheckBox();
        jCheckBox_tatlet = new javax.swing.JCheckBox();
        jCheckBox_crossant = new javax.swing.JCheckBox();
        jCheckBox_rasbCake = new javax.swing.JCheckBox();
        jCheckBox_muffin = new javax.swing.JCheckBox();
        jTextField_cupck = new javax.swing.JTextField();
        jTextField_cheeseck = new javax.swing.JTextField();
        jTextField_tartlt = new javax.swing.JTextField();
        jTextField_crossent = new javax.swing.JTextField();
        jTextField_rasbCake = new javax.swing.JTextField();
        jTextField_muffin = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jText_costDrinks = new javax.swing.JTextField();
        jText_costCakes = new javax.swing.JTextField();
        jText_tax = new javax.swing.JTextField();
        jText_serviceCharg = new javax.swing.JTextField();
        jText_subTot = new javax.swing.JTextField();
        jText_tot = new javax.swing.JTextField();
        jPanel_tea = new javax.swing.JPanel();
        jCheckBox_blackT = new javax.swing.JCheckBox();
        jCheckBox_greenT = new javax.swing.JCheckBox();
        jCheckBox_mintT = new javax.swing.JCheckBox();
        jCheckBox_chocolatT = new javax.swing.JCheckBox();
        jCheckBox_iceT = new javax.swing.JCheckBox();
        jCheckBox_hotChoco = new javax.swing.JCheckBox();
        jTextField_blackT = new javax.swing.JTextField();
        jTextField_greenT = new javax.swing.JTextField();
        jTextField_mintT = new javax.swing.JTextField();
        jTextField_chocolatT = new javax.swing.JTextField();
        jTextField_iceT = new javax.swing.JTextField();
        jTextField_hotChoco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        JbtnRecipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnCal = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_coffee.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Coffee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jCheckBox_blackCoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_blackCoff.setText("Black Coffee");
        jCheckBox_blackCoff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_blackCoffMouseClicked(evt);
            }
        });
        jCheckBox_blackCoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_blackCoffActionPerformed(evt);
            }
        });

        jCheckBox_expresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_expresso.setText("Expresso");
        jCheckBox_expresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_expressoMouseClicked(evt);
            }
        });

        jCheckBox_americano.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_americano.setText("Americano");
        jCheckBox_americano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_americanoMouseClicked(evt);
            }
        });

        jCheckBox_latte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_latte.setText("Latte");
        jCheckBox_latte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_latteMouseClicked(evt);
            }
        });

        jCheckBox_cappuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_cappuccino.setText("Cappuccino");
        jCheckBox_cappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_cappuccinoMouseClicked(evt);
            }
        });

        jCheckBox_mocha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_mocha.setText("Mocha");
        jCheckBox_mocha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_mochaMouseClicked(evt);
            }
        });

        jTextField_expresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_expresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_expresso.setText("0");
        jTextField_expresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_expressoMouseClicked(evt);
            }
        });

        jTextField_americno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_americno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_americno.setText("0");
        jTextField_americno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_americnoMouseClicked(evt);
            }
        });

        jTextField_latte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_latte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_latte.setText("0");
        jTextField_latte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_latteMouseClicked(evt);
            }
        });

        jTextField_cappucino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_cappucino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_cappucino.setText("0");
        jTextField_cappucino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cappucinoMouseClicked(evt);
            }
        });

        jTextField_mocha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_mocha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_mocha.setText("0");
        jTextField_mocha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_mochaMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee-straw.png"))); // NOI18N

        jTextField_blackCoff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_blackCoff.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_blackCoff.setText("0");
        jTextField_blackCoff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_blackCoffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_coffeeLayout = new javax.swing.GroupLayout(jPanel_coffee);
        jPanel_coffee.setLayout(jPanel_coffeeLayout);
        jPanel_coffeeLayout.setHorizontalGroup(
            jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_blackCoff, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                                                .addComponent(jCheckBox_expresso)
                                                .addGap(38, 38, 38)))
                                        .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                                            .addComponent(jCheckBox_americano)
                                            .addGap(22, 22, 22)))
                                    .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                                        .addComponent(jCheckBox_latte)
                                        .addGap(74, 74, 74)))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_americno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_latte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_expresso, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_blackCoff, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_coffeeLayout.createSequentialGroup()
                                    .addComponent(jCheckBox_mocha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_mocha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_coffeeLayout.createSequentialGroup()
                                    .addComponent(jCheckBox_cappuccino)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField_cappucino, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_coffeeLayout.setVerticalGroup(
            jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_coffeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_blackCoff)
                    .addComponent(jTextField_blackCoff, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_expresso)
                    .addComponent(jTextField_expresso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_americano)
                    .addComponent(jTextField_americno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_latte)
                    .addComponent(jTextField_latte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_cappuccino)
                    .addComponent(jTextField_cappucino, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_coffeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_mocha)
                    .addComponent(jTextField_mocha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        getContentPane().add(jPanel_coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 410));

        jPanel_cakes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Cakes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jCheckBox_cupCake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_cupCake.setText("Cupcake");
        jCheckBox_cupCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_cupCakeMouseClicked(evt);
            }
        });

        jCheckBox_cheeseCake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_cheeseCake.setText("Cheesecake");
        jCheckBox_cheeseCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_cheeseCakeMouseClicked(evt);
            }
        });

        jCheckBox_tatlet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_tatlet.setText("Tartlet");
        jCheckBox_tatlet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_tatletMouseClicked(evt);
            }
        });

        jCheckBox_crossant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_crossant.setText("Croissant");
        jCheckBox_crossant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_crossantMouseClicked(evt);
            }
        });

        jCheckBox_rasbCake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_rasbCake.setText("Raspberry Cake");
        jCheckBox_rasbCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_rasbCakeMouseClicked(evt);
            }
        });

        jCheckBox_muffin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_muffin.setText("Muffin");
        jCheckBox_muffin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_muffinMouseClicked(evt);
            }
        });

        jTextField_cupck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_cupck.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_cupck.setText("0");
        jTextField_cupck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cupckMouseClicked(evt);
            }
        });

        jTextField_cheeseck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_cheeseck.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_cheeseck.setText("0");
        jTextField_cheeseck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_cheeseckMouseClicked(evt);
            }
        });

        jTextField_tartlt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_tartlt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_tartlt.setText("0");
        jTextField_tartlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_tartltMouseClicked(evt);
            }
        });

        jTextField_crossent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_crossent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_crossent.setText("0");
        jTextField_crossent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_crossentMouseClicked(evt);
            }
        });

        jTextField_rasbCake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_rasbCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_rasbCake.setText("0");
        jTextField_rasbCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_rasbCakeMouseClicked(evt);
            }
        });

        jTextField_muffin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_muffin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_muffin.setText("0");
        jTextField_muffin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_muffinMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cake-cherry.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_cakesLayout = new javax.swing.GroupLayout(jPanel_cakes);
        jPanel_cakes.setLayout(jPanel_cakesLayout);
        jPanel_cakesLayout.setHorizontalGroup(
            jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jCheckBox_cupCake)
                .addGap(70, 70, 70)
                .addComponent(jTextField_cupck, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jCheckBox_cheeseCake)
                .addGap(38, 38, 38)
                .addComponent(jTextField_cheeseck, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jCheckBox_tatlet)
                .addGap(88, 88, 88)
                .addComponent(jTextField_tartlt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jCheckBox_crossant)
                .addGap(64, 64, 64)
                .addComponent(jTextField_crossent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jCheckBox_rasbCake)
                .addGap(6, 6, 6)
                .addComponent(jTextField_rasbCake, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jCheckBox_muffin)
                .addGap(88, 88, 88)
                .addComponent(jTextField_muffin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel16))
        );
        jPanel_cakesLayout.setVerticalGroup(
            jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cakesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_cupCake)
                    .addGroup(jPanel_cakesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_cupck, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_cheeseCake)
                    .addGroup(jPanel_cakesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_cheeseck, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_tatlet)
                    .addGroup(jPanel_cakesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_tartlt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_crossant)
                    .addGroup(jPanel_cakesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_crossent, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_rasbCake)
                    .addGroup(jPanel_cakesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_rasbCake, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_cakesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_muffin)
                    .addGroup(jPanel_cakesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_muffin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        getContentPane().add(jPanel_cakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, 410));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 124, 400, 410));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel8.setText("Cost of Drinks :");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel9.setText("Cost of Cakes :");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel10.setText("Tax");

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel11.setText("Service Charge :");

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel12.setText("Sub Total  :");

        jLabel13.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel13.setText("Total:");

        jText_costDrinks.setEditable(false);
        jText_costDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jText_costDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_costDrinks.setText("0");
        jText_costDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_costCakes.setEditable(false);
        jText_costCakes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jText_costCakes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_costCakes.setText("0");
        jText_costCakes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_tax.setEditable(false);
        jText_tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jText_tax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_tax.setText("0");
        jText_tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_serviceCharg.setEditable(false);
        jText_serviceCharg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jText_serviceCharg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_serviceCharg.setText("100");
        jText_serviceCharg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_subTot.setEditable(false);
        jText_subTot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jText_subTot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_subTot.setText("0");
        jText_subTot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jText_tot.setEditable(false);
        jText_tot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jText_tot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_tot.setText("0");
        jText_tot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jText_costCakes, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jText_costDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(jText_serviceCharg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jText_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jText_subTot, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_costDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_subTot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_costCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_serviceCharg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 930, -1));

        jPanel_tea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Tea", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jCheckBox_blackT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_blackT.setText("Black Tea");
        jCheckBox_blackT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_blackTMouseClicked(evt);
            }
        });

        jCheckBox_greenT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_greenT.setText("Green Tea");
        jCheckBox_greenT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_greenTMouseClicked(evt);
            }
        });

        jCheckBox_mintT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_mintT.setText("Mint Tea");
        jCheckBox_mintT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_mintTMouseClicked(evt);
            }
        });
        jCheckBox_mintT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_mintTActionPerformed(evt);
            }
        });

        jCheckBox_chocolatT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_chocolatT.setText("Choco. Tea");
        jCheckBox_chocolatT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_chocolatTMouseClicked(evt);
            }
        });

        jCheckBox_iceT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_iceT.setText("Ice Tea");
        jCheckBox_iceT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_iceTMouseClicked(evt);
            }
        });

        jCheckBox_hotChoco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox_hotChoco.setText("Hot Chocolat");
        jCheckBox_hotChoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_hotChocoMouseClicked(evt);
            }
        });

        jTextField_blackT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_blackT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_blackT.setText("0");
        jTextField_blackT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_blackTMouseClicked(evt);
            }
        });

        jTextField_greenT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_greenT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_greenT.setText("0");
        jTextField_greenT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_greenTMouseClicked(evt);
            }
        });

        jTextField_mintT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_mintT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_mintT.setText("0");
        jTextField_mintT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_mintTMouseClicked(evt);
            }
        });

        jTextField_chocolatT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_chocolatT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_chocolatT.setText("0");
        jTextField_chocolatT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_chocolatTMouseClicked(evt);
            }
        });

        jTextField_iceT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_iceT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_iceT.setText("0");
        jTextField_iceT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_iceTMouseClicked(evt);
            }
        });

        jTextField_hotChoco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_hotChoco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_hotChoco.setText("0");
        jTextField_hotChoco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_hotChocoMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tea-cup.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_teaLayout = new javax.swing.GroupLayout(jPanel_tea);
        jPanel_tea.setLayout(jPanel_teaLayout);
        jPanel_teaLayout.setHorizontalGroup(
            jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_teaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_teaLayout.createSequentialGroup()
                        .addComponent(jCheckBox_blackT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_blackT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_teaLayout.createSequentialGroup()
                        .addComponent(jCheckBox_greenT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_greenT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_teaLayout.createSequentialGroup()
                        .addComponent(jCheckBox_mintT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_mintT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_teaLayout.createSequentialGroup()
                        .addComponent(jCheckBox_chocolatT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_chocolatT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_teaLayout.createSequentialGroup()
                        .addComponent(jCheckBox_iceT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_iceT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_teaLayout.createSequentialGroup()
                        .addComponent(jCheckBox_hotChoco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_hotChoco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_teaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(112, 112, 112))
        );
        jPanel_teaLayout.setVerticalGroup(
            jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_teaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_blackT)
                    .addComponent(jTextField_blackT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_greenT)
                    .addComponent(jTextField_greenT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_mintT)
                    .addComponent(jTextField_mintT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_chocolatT)
                    .addComponent(jTextField_chocolatT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_iceT)
                    .addComponent(jTextField_iceT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_teaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_hotChoco)
                    .addComponent(jTextField_hotChoco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel15)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, 410));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setText("N E W   W O R L D   C A F E");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cupcake.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee-to-go.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tea-cup.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restaurant-menu.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restaurant-food-truck.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restaurant-fork-knife.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(63, 63, 63)
                .addComponent(jLabel7)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        JbtnRecipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JbtnRecipt.setText("Recipt");
        JbtnRecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnReciptActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        jbtnCal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCal.setText("Calculator");
        jbtnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JbtnRecipt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jbtnCal, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnRecipt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, 400, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
    
    jText_costCakes.setText("0");
    jText_costDrinks.setText("0");
    jText_serviceCharg.setText("100");
    jText_subTot.setText("0");
    jText_tax.setText("0");
    jText_tot.setText("0");
    
    jTextArea1.setText(null);
    
    jTextField_americno.setText("0");
    jTextField_blackCoff.setText("0");
    jTextField_cappucino.setText("0");
    jTextField_cheeseck.setText("0");
    jTextField_crossent.setText("0");
    jTextField_cupck.setText("0");
    jTextField_expresso.setText("0");
    jTextField_latte.setText("0");
    jTextField_mocha.setText("0");
    jTextField_muffin.setText("0");
    jTextField_rasbCake.setText("0");
    jTextField_tartlt.setText("0");
    jTextField_blackT.setText("0");
    jTextField_greenT.setText("0");
    jTextField_mintT.setText("0");
    jTextField_chocolatT.setText("0");
    jTextField_iceT.setText("0");
    jTextField_hotChoco.setText("0");
    
    jCheckBox_americano.setSelected(false);
    jCheckBox_blackCoff.setSelected(false);
    jCheckBox_cappuccino.setSelected(false);
    jCheckBox_cheeseCake.setSelected(false);
    jCheckBox_crossant.setSelected(false);
    jCheckBox_cupCake.setSelected(false);
    jCheckBox_expresso.setSelected(false);
    jCheckBox_latte.setSelected(false);
    jCheckBox_mocha.setSelected(false);
    jCheckBox_muffin.setSelected(false);
    jCheckBox_rasbCake.setSelected(false);
    jCheckBox_tatlet.setSelected(false);
    jCheckBox_blackT.setSelected(false);
    jCheckBox_greenT.setSelected(false);
    jCheckBox_mintT.setSelected(false);
    jCheckBox_chocolatT.setSelected(false);
    jCheckBox_iceT.setSelected(false);
    jCheckBox_hotChoco.setSelected(false);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void JbtnReciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnReciptActionPerformed
        drink[0] = Double.parseDouble(jTextField_blackCoff.getText());
        drink[1] = Double.parseDouble(jTextField_expresso.getText());
        drink[2] = Double.parseDouble(jTextField_americno.getText());
        drink[3] = Double.parseDouble(jTextField_latte.getText());
        drink[4] = Double.parseDouble(jTextField_cappucino.getText());
        drink[5] = Double.parseDouble(jTextField_mocha.getText());
        drink[6] = Double.parseDouble(jTextField_blackT.getText());
        drink[7] = Double.parseDouble(jTextField_greenT.getText());
        drink[8] = Double.parseDouble(jTextField_mintT.getText());
        drink[9] = Double.parseDouble(jTextField_chocolatT.getText());
        drink[10] =Double.parseDouble(jTextField_iceT.getText());
        drink[11] =Double.parseDouble(jTextField_hotChoco.getText());
        
        cake[0] = Double.parseDouble(jTextField_cupck.getText());
        cake[1] = Double.parseDouble(jTextField_cheeseck.getText());
        cake[2] = Double.parseDouble(jTextField_tartlt.getText());
        cake[3] = Double.parseDouble(jTextField_crossent.getText());
        cake[4] = Double.parseDouble(jTextField_rasbCake.getText());
        cake[5] = Double.parseDouble(jTextField_muffin.getText());
        
        cost[0] = jText_tax.getText();
        cost[1] = jText_subTot.getText();
        cost[2] = jText_tot.getText();
        
        //=========================================================
        int refs;
        refs=1325+(int) (Math.random()*4238);
        
        //=========================================================
                Calendar timer= Calendar.getInstance();
                timer.getTime();
                SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
                tTime.format(timer.getTime());
                SimpleDateFormat tDate=new SimpleDateFormat("dd-MM-yyyy");
                tDate.format(timer.getTime()); 
        //=========================================================
        
        jTextArea1.append("\n\t NEW WORLD CAFE \n\n" +
                "Referance : \t" + refs +
                "\n" +
                 "\n=================D=R=I=N=K=S==================\t\t" +
                 "\n" +
                "\n\t\tQuantaty \tPrice" +         
                "\n Black Coffee \t:\t" + drink[0] + "           *           " + iBlackCoffee +
                "\n Expresso \t:\t" + drink[1] +  "           *           " + iExpresso +
                "\n Americano \t:\t" + drink[2] +  "           *           " + iAmericano +
                "\n Latte \t:\t" + drink[3] +  "           *           " + iLatte +
                "\n Cappuccino \t:\t" + drink[4] +  "           *           " + iCappuccino +
                "\n Mocha \t:\t" + drink[5] +  "           *           " + iMocha +
                "\n Black Tea \t:\t" + drink[6] +  "           *           " + iBlackTea +
                "\n Green Tea \t:\t" + drink[7] +  "           *           " + iGreenTea +
                "\n Mint Tea \t:\t" + drink[8] +  "           *           " + iMintTea +
                "\n Chocolet Tea \t:\t" + drink[9] +  "           *           " + iChocoletTea +
                "\n Ice Tea \t:\t" + drink[10] +  "           *           " + iIceTea +
                "\n Hot Chocolet \t:\t" + drink[11] +  "           *           " + iHotChocolet +
                "\n" + 
                "\n=================C=A=K=E=S=====================\t\t" +
                "\n" + 
                "\n Cupcake \t:\t" + cake[0] +  "           *           " + iCupcake +
                "\n Cheesecake \t:\t" + cake[1] +  "           *           " + iCheesecake +
                "\n Tartlet \t:\t" + cake[2] +  "           *           " + iTartlet +
                "\n Crossaint \t:\t" + cake[3] +  "           *           " + iCrossaint +
                "\n Raspberry Cake:\t" + cake[4] +  "           *           " + iRaspberry +
                "\n Muffin \t:\t" + cake[5] +  "           *           " + iMuffin +
                "\n" + 
                "\n================================================\t\t" +
                "\n Tax \t:\t\t" + cost[0] +
                "\n Sub Total \t:\t\t" + cost[1] +
                "\n Total \t:\t\t" + cost[2] +
                 "\n" + 
                "\n ** ++Service Charge " +
                "\n================================================\t\t" +
                "\n Date : " + tDate.format(timer.getTime()) +
                "\t\t Time : " + tTime.format(timer.getTime()) +
                "\n\n\t\t Thank You!");
                
    }//GEN-LAST:event_JbtnReciptActionPerformed

    private void jCheckBox_mintTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_mintTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_mintTActionPerformed

    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       frame=new JFrame();
       if(JOptionPane.showConfirmDialog(frame, "Do you really want to exit ?","Cafe Management",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jCheckBox_blackCoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_blackCoffActionPerformed
  
    }//GEN-LAST:event_jCheckBox_blackCoffActionPerformed

    private void jCheckBox_blackCoffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_blackCoffMouseClicked
        double cBlackCoffee = Double.parseDouble(jText_costDrinks.getText());
        double BlackCoffee = Double.parseDouble(jTextField_blackCoff.getText());
        
        if (jCheckBox_blackCoff.isSelected())
        {
            i[0] = (BlackCoffee * iBlackCoffee) + cBlackCoffee; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_blackCoffMouseClicked

    private void jCheckBox_expressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_expressoMouseClicked
        double cExpresso = Double.parseDouble(jText_costDrinks.getText());
        double Expresso = Double.parseDouble(jTextField_expresso.getText());
        
        if (jCheckBox_expresso.isSelected())
        {
            i[1] = (Expresso * iExpresso) + cExpresso;
            String pDrink = String.format("%.2f", i[1]);
            jText_costDrinks.setText(pDrink);  
        }
    }//GEN-LAST:event_jCheckBox_expressoMouseClicked

    private void jCheckBox_americanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_americanoMouseClicked
        double cAmericano = Double.parseDouble(jText_costDrinks.getText());
        double Americano = Double.parseDouble(jTextField_americno.getText());
        
        if (jCheckBox_americano.isSelected())
        {
            i[0] = (Americano * iAmericano) + cAmericano; // iAmericano value is price of one americano
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_americanoMouseClicked

    private void jCheckBox_latteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_latteMouseClicked
       double cLatte = Double.parseDouble(jText_costDrinks.getText());
        double Latte = Double.parseDouble(jTextField_latte.getText());
        
        if (jCheckBox_latte.isSelected())
        {
            i[0] = (Latte * iLatte) + cLatte; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_latteMouseClicked

    private void jCheckBox_cappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_cappuccinoMouseClicked
        double cCappuccino = Double.parseDouble(jText_costDrinks.getText());
        double Cappuccino = Double.parseDouble(jTextField_cappucino.getText());
        
        if (jCheckBox_cappuccino.isSelected())
        {
            i[0] = (Cappuccino * iCappuccino) + cCappuccino; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_cappuccinoMouseClicked

    private void jCheckBox_mochaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_mochaMouseClicked
        double cMocha = Double.parseDouble(jText_costDrinks.getText());
        double Mocha = Double.parseDouble(jTextField_mocha.getText());
        
        if (jCheckBox_mocha.isSelected())
        {
            i[0] = (Mocha * iMocha) + cMocha; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_mochaMouseClicked

    private void jCheckBox_blackTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_blackTMouseClicked
        double cBlackTea = Double.parseDouble(jText_costDrinks.getText());
        double BlackTea = Double.parseDouble(jTextField_blackT.getText());
        
        if (jCheckBox_blackT.isSelected())
        {
            i[0] = (BlackTea * iBlackTea) + cBlackTea; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_blackTMouseClicked

    private void jCheckBox_greenTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_greenTMouseClicked
        double cGreenTea = Double.parseDouble(jText_costDrinks.getText());
        double GreenTea = Double.parseDouble(jTextField_greenT.getText());
        
        if (jCheckBox_greenT.isSelected())
        {
            i[0] = (GreenTea * iGreenTea) + cGreenTea; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_greenTMouseClicked

    private void jCheckBox_mintTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_mintTMouseClicked
        double cMintTea = Double.parseDouble(jText_costDrinks.getText());
        double MintTea = Double.parseDouble(jTextField_mintT.getText());
        
        if (jCheckBox_mintT.isSelected())
        {
            i[0] = (MintTea * iMintTea) + cMintTea; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_mintTMouseClicked

    private void jCheckBox_chocolatTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_chocolatTMouseClicked
        double cChocoletTea = Double.parseDouble(jText_costDrinks.getText());
        double ChocoletTea = Double.parseDouble(jTextField_chocolatT.getText());
        
        if (jCheckBox_chocolatT.isSelected())
        {
            i[0] = (ChocoletTea * iChocoletTea) + cChocoletTea; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_chocolatTMouseClicked

    private void jCheckBox_iceTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_iceTMouseClicked
        double cIceTea = Double.parseDouble(jText_costDrinks.getText());
        double IceTea = Double.parseDouble(jTextField_iceT.getText());
        
        if (jCheckBox_iceT.isSelected())
        {
            i[0] = (IceTea * iIceTea) + cIceTea; // i"BlackCoffee" value is price of one given item (BlackCoffee)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_iceTMouseClicked

    private void jCheckBox_hotChocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_hotChocoMouseClicked
        double cHotChocolate = Double.parseDouble(jText_costDrinks.getText());
        double HotChocolate = Double.parseDouble(jTextField_hotChoco.getText());
        
        if (jCheckBox_hotChoco.isSelected())
        {
            i[0] = (HotChocolate * iHotChocolet) + cHotChocolate; // i"HotChocolet" value is price of one given item (HotChocolet)
            String pDrink = String.format("%.2f", i[0]);
            jText_costDrinks.setText(pDrink);   
        }
    }//GEN-LAST:event_jCheckBox_hotChocoMouseClicked

    private void jCheckBox_cupCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_cupCakeMouseClicked
        double cCupcake = Double.parseDouble(jText_costCakes.getText());
        double Cupcake = Double.parseDouble(jTextField_cupck.getText());
        
        if(jCheckBox_cupCake.isSelected())
        {
            i[12] = (Cupcake * iCupcake) + cCupcake;
            String pCupcake = String.format("%.2f", i[12]);
            jText_costCakes.setText(pCupcake);
        }
    }//GEN-LAST:event_jCheckBox_cupCakeMouseClicked

    private void jCheckBox_cheeseCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_cheeseCakeMouseClicked
        double cCheesecake = Double.parseDouble(jText_costCakes.getText());
        double Cheesecake = Double.parseDouble(jTextField_cheeseck.getText());
        
        if(jCheckBox_cheeseCake.isSelected())
        {
            i[12] = (Cheesecake * iCheesecake) + cCheesecake;
            String pCupcake = String.format("%.2f", i[12]);
            jText_costCakes.setText(pCupcake);
        }
    }//GEN-LAST:event_jCheckBox_cheeseCakeMouseClicked

    private void jCheckBox_tatletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_tatletMouseClicked
        double cTartlet = Double.parseDouble(jText_costCakes.getText());
        double Tartlet = Double.parseDouble(jTextField_tartlt.getText());
        
        if(jCheckBox_tatlet.isSelected())
        {
            i[12] = (Tartlet * iTartlet) + cTartlet;
            String pCupcake = String.format("%.2f", i[12]);
            jText_costCakes.setText(pCupcake);
        }
    }//GEN-LAST:event_jCheckBox_tatletMouseClicked

    private void jCheckBox_crossantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_crossantMouseClicked
        double cCrossaint = Double.parseDouble(jText_costCakes.getText());
        double Crossaint = Double.parseDouble(jTextField_crossent.getText());
        
        if(jCheckBox_crossant.isSelected())
        {
            i[12] = (Crossaint * iCrossaint) + cCrossaint;
            String pCupcake = String.format("%.2f", i[12]);
            jText_costCakes.setText(pCupcake);
        }
    }//GEN-LAST:event_jCheckBox_crossantMouseClicked

    private void jCheckBox_rasbCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_rasbCakeMouseClicked
        double cRaspberry = Double.parseDouble(jText_costCakes.getText());
        double Raspberry = Double.parseDouble(jTextField_rasbCake.getText());
        
        if(jCheckBox_rasbCake.isSelected())
        {
            i[12] = (Raspberry * iRaspberry) + cRaspberry;
            String pCupcake = String.format("%.2f", i[12]);
            jText_costCakes.setText(pCupcake);
        }
    }//GEN-LAST:event_jCheckBox_rasbCakeMouseClicked

    private void jCheckBox_muffinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_muffinMouseClicked
        double cMuffin = Double.parseDouble(jText_costCakes.getText());
        double Muffin = Double.parseDouble(jTextField_muffin.getText());
        
        if(jCheckBox_muffin.isSelected())
        {
            i[12] = (Muffin * iMuffin) + cMuffin;
            String pCupcake = String.format("%.2f", i[12]);
            jText_costCakes.setText(pCupcake);
        }
    }//GEN-LAST:event_jCheckBox_muffinMouseClicked

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        
        ncost[0] = Double.parseDouble(jText_costDrinks.getText());
        ncost[1] = Double.parseDouble(jText_costCakes.getText());
        ncost[2] = Double.parseDouble(jText_serviceCharg.getText());
        
        double cTotal = (ncost[0] + ncost[1] + ncost[2]);
        
        String iTax = String.format("Rs. %.2f", cTotal/100);
        jText_tax.setText(iTax);
        
        double subTotal = (cTotal);
        String isubTotal = String.format("Rs. %.2f", subTotal);
        jText_subTot.setText(isubTotal);
        
        double finalTotal = (cTotal);
        String ifinalTotal = String.format("Rs. %.2f", finalTotal + (finalTotal/100));
        jText_tot.setText(ifinalTotal);
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
       try
        {
            jTextArea1.print();
            
        }
        catch(PrinterException ex)
        {
            Logger.getLogger(cafe2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jTextField_blackCoffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_blackCoffMouseClicked
        jTextField_blackCoff.setText(null);
    }//GEN-LAST:event_jTextField_blackCoffMouseClicked

    private void jTextField_expressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_expressoMouseClicked
        jTextField_expresso.setText(null);
    }//GEN-LAST:event_jTextField_expressoMouseClicked

    private void jTextField_americnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_americnoMouseClicked
        jTextField_americno.setText(null);
    }//GEN-LAST:event_jTextField_americnoMouseClicked

    private void jTextField_latteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_latteMouseClicked
        jTextField_latte.setText(null);
    }//GEN-LAST:event_jTextField_latteMouseClicked

    private void jTextField_cappucinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cappucinoMouseClicked
        jTextField_cappucino.setText(null);
    }//GEN-LAST:event_jTextField_cappucinoMouseClicked

    private void jTextField_mochaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_mochaMouseClicked
        jTextField_mocha.setText(null);
    }//GEN-LAST:event_jTextField_mochaMouseClicked

    private void jTextField_blackTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_blackTMouseClicked
        jTextField_blackT.setText(null);
    }//GEN-LAST:event_jTextField_blackTMouseClicked

    private void jTextField_greenTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_greenTMouseClicked
        jTextField_greenT.setText(null);
    }//GEN-LAST:event_jTextField_greenTMouseClicked

    private void jTextField_mintTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_mintTMouseClicked
        jTextField_mintT.setText(null);
    }//GEN-LAST:event_jTextField_mintTMouseClicked

    private void jTextField_chocolatTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_chocolatTMouseClicked
        jTextField_chocolatT.setText(null);
    }//GEN-LAST:event_jTextField_chocolatTMouseClicked

    private void jTextField_iceTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_iceTMouseClicked
       jTextField_iceT.setText(null);
    }//GEN-LAST:event_jTextField_iceTMouseClicked

    private void jTextField_hotChocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_hotChocoMouseClicked
        jTextField_hotChoco.setText(null);
    }//GEN-LAST:event_jTextField_hotChocoMouseClicked

    private void jTextField_cupckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cupckMouseClicked
        jTextField_cupck.setText(null);
    }//GEN-LAST:event_jTextField_cupckMouseClicked

    private void jTextField_cheeseckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_cheeseckMouseClicked
        jTextField_cheeseck.setText(null);
    }//GEN-LAST:event_jTextField_cheeseckMouseClicked

    private void jTextField_tartltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_tartltMouseClicked
        jTextField_tartlt.setText(null);
    }//GEN-LAST:event_jTextField_tartltMouseClicked

    private void jTextField_crossentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_crossentMouseClicked
        jTextField_crossent.setText(null);
    }//GEN-LAST:event_jTextField_crossentMouseClicked

    private void jTextField_rasbCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_rasbCakeMouseClicked
        jTextField_rasbCake.setText(null);
    }//GEN-LAST:event_jTextField_rasbCakeMouseClicked

    private void jTextField_muffinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_muffinMouseClicked
        jTextField_muffin.setText(null);
    }//GEN-LAST:event_jTextField_muffinMouseClicked

    private void jbtnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalActionPerformed
        new Calculator().setVisible(true);
    }//GEN-LAST:event_jbtnCalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafe2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cafe2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnRecipt;
    private javax.swing.JCheckBox jCheckBox_americano;
    private javax.swing.JCheckBox jCheckBox_blackCoff;
    private javax.swing.JCheckBox jCheckBox_blackT;
    private javax.swing.JCheckBox jCheckBox_cappuccino;
    private javax.swing.JCheckBox jCheckBox_cheeseCake;
    private javax.swing.JCheckBox jCheckBox_chocolatT;
    private javax.swing.JCheckBox jCheckBox_crossant;
    private javax.swing.JCheckBox jCheckBox_cupCake;
    private javax.swing.JCheckBox jCheckBox_expresso;
    private javax.swing.JCheckBox jCheckBox_greenT;
    private javax.swing.JCheckBox jCheckBox_hotChoco;
    private javax.swing.JCheckBox jCheckBox_iceT;
    private javax.swing.JCheckBox jCheckBox_latte;
    private javax.swing.JCheckBox jCheckBox_mintT;
    private javax.swing.JCheckBox jCheckBox_mocha;
    private javax.swing.JCheckBox jCheckBox_muffin;
    private javax.swing.JCheckBox jCheckBox_rasbCake;
    private javax.swing.JCheckBox jCheckBox_tatlet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_cakes;
    private javax.swing.JPanel jPanel_coffee;
    private javax.swing.JPanel jPanel_tea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_americno;
    private javax.swing.JTextField jTextField_blackCoff;
    private javax.swing.JTextField jTextField_blackT;
    private javax.swing.JTextField jTextField_cappucino;
    private javax.swing.JTextField jTextField_cheeseck;
    private javax.swing.JTextField jTextField_chocolatT;
    private javax.swing.JTextField jTextField_crossent;
    private javax.swing.JTextField jTextField_cupck;
    private javax.swing.JTextField jTextField_expresso;
    private javax.swing.JTextField jTextField_greenT;
    private javax.swing.JTextField jTextField_hotChoco;
    private javax.swing.JTextField jTextField_iceT;
    private javax.swing.JTextField jTextField_latte;
    private javax.swing.JTextField jTextField_mintT;
    private javax.swing.JTextField jTextField_mocha;
    private javax.swing.JTextField jTextField_muffin;
    private javax.swing.JTextField jTextField_rasbCake;
    private javax.swing.JTextField jTextField_tartlt;
    private javax.swing.JTextField jText_costCakes;
    private javax.swing.JTextField jText_costDrinks;
    private javax.swing.JTextField jText_serviceCharg;
    private javax.swing.JTextField jText_subTot;
    private javax.swing.JTextField jText_tax;
    private javax.swing.JTextField jText_tot;
    private javax.swing.JButton jbtnCal;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    // End of variables declaration//GEN-END:variables
}
